### ISSUE TITLE
Could not find executable pandoc_filter.py

### ISSUE THREAD

**Issue by jantielens** [mwiget/pandoc-mermaid#1]
Hi, I'm trying to use this to generate a PDF containing our mermaid diagrams. Unfortunately when I run the command
```bash
sudo docker run -ti --rm -u `id -u $USER` --cap-add=SYS_ADMIN -v $PWD:/u \
  marcelwiget/pandoc-mermaid \
  pandoc --pdf-engine=xelatex \
  --filter=pandoc_filter.py \
  *.md -o example.pdf
```
I get the error
```
Error running filter pandoc_filter.py:
Could not find executable pandoc_filter.py
```

When I run the command without the --filter param, it works as expected (the mermaid diagrams are not generated of course :) ).
```bash
sudo docker run -ti --rm -u `id -u $USER` --cap-add=SYS_ADMIN -v $PWD:/u \
  marcelwiget/pandoc-mermaid \
  pandoc --pdf-engine=xelatex \
  *.md -o example.pdf
```

Thanks for any tips to solve this!
J

**Comment by mwiget** [comment]
Try making the pandoc_filter.py executable with 'chmod a+x pandoc_filter.py'. I know, seems strange, but that's what I needed. I assume you have that file in the current folder as this repo does.

**Comment by jantielens** [comment]
Thanks for the swift reply! So I didn't have the pandoc_filter.py locally. So I downloaded it, gave it permissions, and now the output is:
```
Traceback (most recent call last):
  File "./pandoc_filter.py", line 321, in <module>
    main()
  File "./pandoc_filter.py", line 317, in main
    doc=doc)
  File "/usr/local/lib/python3.6/dist-packages/panflute/io.py", line 239, in run_filters
    doc = doc.walk(action, doc)
  File "/usr/local/lib/python3.6/dist-packages/panflute/base.py", line 265, in walk
    ans = list(chain.from_iterable(ans))
  File "/usr/local/lib/python3.6/dist-packages/panflute/base.py", line 263, in <genexpr>
    ans = ((item,) if type(item) != list else item for item in ans)
  File "/usr/local/lib/python3.6/dist-packages/panflute/base.py", line 260, in <genexpr>
    ans = (item.walk(action, doc) for item in obj)
  File "/usr/local/lib/python3.6/dist-packages/panflute/base.py", line 276, in walk
    altered = action(self, doc)
  File "./pandoc_filter.py", line 58, in process_mermaid
    with open(src, "wb") as f:
PermissionError: [Errno 13] Permission denied: 'mermaid-images/c92aa732bd085e51bf57177b7ec4fdc38525e7e1.mmd'
Error running filter pandoc_filter.py:
Filter returned error status 1
```

**Comment by jantielens** [comment]
I had the mermaid-images folder locally, deleting it now ...
